# Generated by Django 2.2.6 on 2019-10-15 19:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.BooleanField(default=False)),
                ('DateTimeSent', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('SentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID_SentBy', to=settings.AUTH_USER_MODEL)),
                ('SentTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID_SentTo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendSince', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('FriendID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID_FriendID', to=settings.AUTH_USER_MODEL)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserID_MyID', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
