# Generated by Django 2.2.6 on 2019-10-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='embarked',
            field=models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1),
        ),
    ]
