# Generated by Django 2.2.6 on 2019-10-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='User_ID',
            field=models.IntegerField(default=0),
        ),
    ]
